((nil . ((projectile-project-compilation-cmd . "cmake ..")
         (projectile-project-compilation-dir . "build/")
         (projectile-project-run-cmd . "~/programacion/qt/libroskop/build/libroskop")
         (projectile-project-name . "libroskop")
         )))
